version: '3.8'

services:

  app:
    image: node:20-slim
    container_name: interpreter-booking-app
    working_dir: /app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: "1"
      # Prisma/DB connection to the mysql service
      DATABASE_URL: mysql://STGOGK:P@ssw0rd@192.168.1.58:3306/booking_interpreter
      # Optional: enable reliable file watching inside containers on Windows/Mac
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    command: >-
      sh -c "npm ci || npm install && npx prisma migrate deploy && npm run dev"

volumes:
  mysql_data:
  node_modules:
  next_cache:
